trailingComma: all
semi: false
useTabs: true
singleQuote: true
bracketSameLine: false

plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.astro'
    options:
      parser: astro
